/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mazesolver;

import static junit.framework.Assert.assertNotNull;
import org.junit.Test;



public class AppTest {
    @Test 
        public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
